# Site
title:              邹勇的个人空间
bio:                我是一个前端er
description:        "邹勇的个人空间"
keywords:           "Web前端, 前端开发, 邹勇博客, 个人博客"
#reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
#background:         http://i.imgur.com/Ds6S7lJ.png
locale:             en_US
url:                https://zouyongzou.github.io
#url:                http://127.0.0.1:4000


# Jekyll
permalink:          /:title/
markdown:           kramdown
excerpt_separator:  "<!--more-->"
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   zouyongzou

# 阅读次数
leancloud:
  enable: true
  app_id: 9wsnJbHIUAY3d4PrKsg6q92H-gzGzoHsz
  app_key: mAEpionhrt3pmDw3Lol6sRoN

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#twitter:            username
#facebook:           username
github-url:         zouyongzou
email:              zouyongzou@foxmail.com
qq:                 http://wpa.qq.com/msgrd?v=3&uin=854479948&site=qq&menu=yes
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
# weibo:            username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
